name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable
    
        - uses: actions/checkout@v4 #checkout working dir
        - name: install xcbeautify #human friendly logs
          run: brew install xcbeautify
      
        - name: Set up mapbox secret file
          env:
            MAPBOX_SECRET_KEY: ${{ secrets.MAPBOX_CI_ACCESS_TOKEN }}
          run: |
            echo "machine api.mapbox.com" >> ~/.netrc
            echo "login mapbox" >> ~/.netrc
            echo "password $MAPBOX_SECRET_KEY" >> ~/.netrc
        - name: Run the xcode tests
          run: set -o pipefail && xcodebuild clean test -project Canyoneer/Canyoneer.xcodeproj -scheme Canyoneer -destination "platform=iOS Simulator,name=iPhone 16" | xcbeautify